version: '3'
services:
  rqlite:
    image: rqlite/rqlite:latest
    ports:
      - '5001:4001' # Expose rqlite's HTTP API
    environment:
      - JOIN=localhost:4001 # Join an existing rqlite cluster (if applicable)

  nodered:
    image: nodered/node-red:latest
    ports:
      - '1880:1880' # Expose Node-RED's UI
    volumes:
      - ./rqlite-storage.mjs:/data/rqlite-storage.mjs
      - ./settings.mjs:/data/settings.mjs # Custom settings if needed
    depends_on:
      - rqlite
